export type Mnemonic = {
  questionId: number;
  topic: string;
  question: string;
  answer: string;
  mnemonic: string;
  hook: string;
};

export const MNEMONICS: Mnemonic[] = [
  {
    questionId: 1,
    topic: "Motor Starting",
    question: "Motors started at reduced voltage must be switched to line voltage to reach ______.",
    answer: "full speed",
    mnemonic: "\"Reduced start, FULL SPEED ahead!\"",
    hook: "A ship slows to enter port, then goes FULL SPEED in open water. Same idea — motor starts slow, must reach full speed.",
  },
  {
    questionId: 2,
    topic: "Motor Starting",
    question: "Starting large HP motors causes significant ______ on the distribution system.",
    answer: "voltage drops",
    mnemonic: "\"Big motors DROP the voltage like a heavy weight drops in a pool.\"",
    hook: "Big inrush current = big resistance × current = big voltage DROP across the system impedance.",
  },
  {
    questionId: 3,
    topic: "Motor Starting",
    question: "In a(n) ______ transition, the motor is briefly disconnected while switching from reduced to full voltage.",
    answer: "open circuit",
    mnemonic: "\"OPEN the gate to switch lanes.\"",
    hook: "The motor is literally disconnected (open circuit) during the transition — like opening a gate to switch roads.",
  },
  {
    questionId: 4,
    topic: "Motor Starting",
    question: "Coil voltage in wye circuit = line voltage divided by ______.",
    answer: "1.73",
    mnemonic: "\"1-7-3: One Wye Three-phase\" or just memorize: 480÷1.73=277, 208÷1.73=120.",
    hook: "√3 = 1.732. Wye coil sees line-to-neutral voltage. 480V system → 277V per coil. 208V → 120V per coil.",
  },
  {
    questionId: 5,
    topic: "Solid-State Devices & Motor Control",
    question: "Which microprocessor function provides a valuable troubleshooting tool?",
    answer: "Self-diagnosis",
    mnemonic: "\"A smart device is like a DOCTOR — it DIAGNOSES ITSELF.\"",
    hook: "Self-diagnosis = the smart relay checks itself and reports faults, like a car's check-engine system.",
  },
  {
    questionId: 6,
    topic: "Solid-State Devices & Motor Control",
    question: "A device used to minimize effects of field device power on the controller is called a(n) ______.",
    answer: "Opto-isolator",
    mnemonic: "\"OPTICS keep things ISOLATED — light crosses the gap, but voltage can't follow.\"",
    hook: "An LED shines light across a gap to a phototransistor. Electricity stops, signal continues. That's opto-isolation.",
  },
  {
    questionId: 7,
    topic: "Solid-State Devices & Motor Control",
    question: "The ESD warning symbol on packaging means ______.",
    answer: "CAUTION – ESD Sensitive Components",
    mnemonic: "\"The hand with the lightning bolt = HANDS OFF, this is sensitive to sparks.\"",
    hook: "The symbol literally shows a hand being struck — it warns: ESD can zap these parts. Sensitive Components.",
  },
  {
    questionId: 8,
    topic: "Solid-State Devices & Motor Control",
    question: "Max OL protection — 40 hp, 208 V, 3Ø, nameplate 112 A, SF 1.15, starting NOT a problem.",
    answer: "140 A",
    mnemonic: "\"112 plus a quarter = 140. SF good, no start problem = 125%.\"",
    hook: "112 × 1.25 = 140. SF ≥ 1.15 + no start issue = 125% rule. Clean multiply.",
  },
  {
    questionId: 9,
    topic: "Motor Overload Protection",
    question: "To size a separate motor overload device, use the motor's ______ current.",
    answer: "nameplate",
    mnemonic: "\"The motor wears its NAME, you use its nameplate to protect it.\"",
    hook: "Overload protection uses actual nameplate FLA (not the NEC table value) — it's personal to THAT specific motor.",
  },
  {
    questionId: 10,
    topic: "Motor Overload Protection",
    question: "The NEC intent is that overload protection protects from ______ current.",
    answer: "overload",
    mnemonic: "\"OVERLOAD protection protects from OVERLOAD. The name says it all!\"",
    hook: "Not short-circuit, not ground-fault — those are separate. Overload protects from sustained overcurrent that builds heat.",
  },
  {
    questionId: 11,
    topic: "Motor Overload Protection",
    question: "Max OL — 25 hp, 240 V, 3Ø, 65 A, SF 1.05, starting IS a problem.",
    answer: "84.5 A",
    mnemonic: "\"SF too small (1.05), starting trouble — bump to 130%. 65 × 1.3 = 84.5.\"",
    hook: "SF < 1.15 + starting IS a problem → 130%. 65 × 1.30 = 84.5. Remember: 130% for small SF with start trouble.",
  },
  {
    questionId: 12,
    topic: "Solid-State Relays",
    question: "A non-programmable solid-state relay has ______.",
    answer: "no moving parts",
    mnemonic: "\"SOLID state = SOLID as a rock = NO MOVING PARTS.\"",
    hook: "Solid-state means semiconductor devices — transistors, SCRs, TRIACs. Nothing mechanical. No contacts, no coil, no spring.",
  },
  {
    questionId: 13,
    topic: "Solid-State Relays",
    question: "Which is NOT a common SSR switching method?",
    answer: "Slim line",
    mnemonic: "\"SSR switching: ZIP — Zero-cross, Instant, Peak. No Slim.\"",
    hook: "Slim line is a lighting product line, not an SSR switching method. The three real ones: Zero-cross, Instant-on, Peak.",
  },
  {
    questionId: 14,
    topic: "Solid-State Relays",
    question: "Which is an advantage of an SSR over an electromechanical relay?",
    answer: "Very fast switching capability",
    mnemonic: "\"SSR switches at the SPEED OF ELECTRICITY — no mechanical delay.\"",
    hook: "No contacts to open/close = microsecond switching. EMRs take milliseconds to move. SSR = very fast.",
  },
  {
    questionId: 15,
    topic: "Class I Hazardous Locations",
    question: "Which wiring method is NOT permitted in Class I, Division 1?",
    answer: "Non-metallic sheathed cable",
    mnemonic: "\"Class I needs ARMOR (metal). NM cable is PLASTIC — no plastic in a gas bomb zone.\"",
    hook: "NM (Romex) has a plastic jacket — no protection against damage in hazardous areas. Only metallic methods allowed in Div 1.",
  },
  {
    questionId: 16,
    topic: "Class I Hazardous Locations",
    question: "Which NEC requirements apply to hazardous location wiring?",
    answer: "All other NEC articles as modified by Articles 500–504",
    mnemonic: "\"500s MODIFY the rest. Start with all of NEC, then let 500–504 change the rules.\"",
    hook: "Hazardous location rules don't replace the whole NEC — they modify it. Everything in Chapters 1–4 still applies, just modified by 500–504.",
  },
  {
    questionId: 17,
    topic: "Class I Hazardous Locations",
    question: "Explosion-proof equipment is designed to ______.",
    answer: "Contain an explosion inside the enclosure and extinguish the flames",
    mnemonic: "\"EXplosion-proof = CONTAINS the EXplosion. The box survives from the INSIDE out.\"",
    hook: "It doesn't prevent explosions or keep gas out. It lets the explosion happen inside and extinguishes it before flames escape.",
  },
  {
    questionId: 18,
    topic: "Class I Hazardous Locations",
    question: "For transformer ≤1,000 V, secondary current 3 A: secondary OCPD may be sized up to ______ when both primary and secondary protection is provided.",
    answer: "167%",
    mnemonic: "\"Tiny secondary (3 amps) = 167%. Remember: low secondary amps = more OCPD flexibility.\"",
    hook: "NEC allows 167% for small-current secondaries (≤9A for some cases) because the transformer itself limits fault current. 167% ≈ 1⅔×.",
  },
  {
    questionId: 19,
    topic: "Transformer Protection",
    question: "For transformers ≤1,000 V with coordinated thermal overload protection, primary OCPD can be set at ______ rated current.",
    answer: "6 times",
    mnemonic: "\"Thermal overload protection buys you 6X freedom on the primary.\"",
    hook: "NEC 450.3(B): if transformer has coordinated thermal OL protection, primary fuse can go up to 600% (6×) of primary FLA.",
  },
  {
    questionId: 20,
    topic: "Transformer Protection",
    question: "Max primary fuses for 250 kVA, 3Ø, 13.2 kV transformer (Z = 3.25%), unsupervised.",
    answer: "35 A",
    mnemonic: "\"250kVA ÷ 13.2kV ÷ 1.732 = 10.93A primary. × 300% = 32.8A → 35A fuse.\"",
    hook: "Primary FLA = kVA ÷ (kV × 1.732) = 10.93A. Low impedance (≤6%) unsupervised = 300% max for fuses → 32.8A → next standard size is 35A.",
  },
  {
    questionId: 21,
    topic: "Transformer Protection",
    question: "Max primary CB for 250 kVA, 3Ø, 13.2 kV transformer (Z = 7.25%), unsupervised.",
    answer: "45 A",
    mnemonic: "\"Same transformer, HIGH impedance (7.25%) = 400% for CB. 10.93 × 4 = 43.7A → 45A.\"",
    hook: "High-Z (>6%) bumps the CB percentage to 400%. 10.93A × 400% = 43.72A → next standard size 45A.",
  },
  {
    questionId: 22,
    topic: "Motor Disconnect Sizing",
    question: "Maximum LRC of a 7½ hp, 460 V, 3Ø motor with Code Letter M.",
    answer: "105 A",
    mnemonic: "\"Code M = 10–11.2 kVA/hp. 7.5hp × 11.19 × 1000 ÷ (460 × 1.732) ≈ 105A.\"",
    hook: "LRC formula: HP × kVA/hp_max × 1000 ÷ (V × 1.732). Code M upper limit = 11.19 kVA/hp.",
  },
  {
    questionId: 23,
    topic: "Motor Disconnect Sizing",
    question: "Minimum disconnect ampacity for a 30 hp, 208 V, 3Ø motor.",
    answer: "101.2 A",
    mnemonic: "\"30hp/208V table FLC = 88A. × 115% = 101.2A. ONE-fifteen for disconnects.\"",
    hook: "Conductors get 125%, disconnects get 115%. Table 430.250: 30hp/208V = 88A. 88 × 1.15 = 101.2.",
  },
  {
    questionId: 24,
    topic: "Motor Disconnect Sizing",
    question: "Motor disconnecting means shall have an ampere rating of at least ______ of motor FLC.",
    answer: "115%",
    mnemonic: "\"1-1-5: ONE-ONE-FIVE for the DISCONNECT. (125 is for CONDUCTORS.)\"",
    hook: "Easy to mix up 115% and 125%. Rule: DISconnect = 115%, CONductors = 125%. D before C in alphabet, 115 < 125.",
  },
  {
    questionId: 25,
    topic: "Motor Disconnect Sizing",
    question: "When installing or maintaining a MCC, an electrician uses the ______ manuals.",
    answer: "manufacturer's",
    mnemonic: "\"The MAKER knows best. Use the MANUFACTURER'S manual.\"",
    hook: "MCCs vary by brand — Square D, Eaton, Siemens all differ. Always use the specific manufacturer's manual for that unit.",
  },
  {
    questionId: 26,
    topic: "Motor Control Centers",
    question: "With MCC unit door open and handle ON, interlocks ______ removal of the unit.",
    answer: "prevent",
    mnemonic: "\"DOOR OPEN + POWER ON = LOCKED IN. Interlocks PREVENT you from pulling a live unit.\"",
    hook: "Safety interlock: you can't pull a unit out while it's energized (handle ON, door open). Prevents arc flash injury.",
  },
  {
    questionId: 27,
    topic: "Motor Control Centers",
    question: "MCC bus bar is usually made of ______.",
    answer: "copper",
    mnemonic: "\"C is for Copper. C is for Control Center. C-C.\"",
    hook: "MCC bus bars are copper for maximum conductivity and minimal heat rise. Copper beats aluminum for compact switchgear buses.",
  },
  {
    questionId: 28,
    topic: "Motor Control Centers",
    question: "MCC classes are ______ and ______.",
    answer: "1, 2",
    mnemonic: "\"MCCs come in 2 classes, named 1 and 2. No 3, no 4 — just 1 and 2.\"",
    hook: "Class 1: individual units fully wired at the factory. Class 2: some wiring done in the field. Just two classes.",
  },
  {
    questionId: 29,
    topic: "Motor Control Centers",
    question: "The MCC term ______ (sometimes called a bucket) refers to a control or plug-in assembly.",
    answer: "unit",
    mnemonic: "\"A UNIT is a bucket — one self-contained starter UNIT that plugs in.\"",
    hook: "The 'bucket' is the slang term; the proper NEC/NEMA term is 'unit'. Each unit is a complete motor starter assembly.",
  },
  {
    questionId: 30,
    topic: "Motor Branch Circuits",
    question: "FLC for a 3Ø, 7½ hp induction motor at 208 V.",
    answer: "24.2 A",
    mnemonic: "\"7.5hp at 208V = 24.2A. Rhyme: Seven-point-five at TWO-OH-EIGHT, gives TWO-FOUR-POINT-TWO that's great.\"",
    hook: "Straight table lookup — NEC Table 430.250. 7.5hp/208V = 24.2A. Memorize the common ones.",
  },
  {
    questionId: 31,
    topic: "Motor Branch Circuits",
    question: "Smallest copper THW conductor for a 25 hp, 480 V, 3Ø motor-compressor (selection current 45 A).",
    answer: "6 AWG",
    mnemonic: "\"45A × 125% = 56.25A. 6 AWG THW = 65A. SIX AWG for the SIX-ty-five amp wire.\"",
    hook: "Motor-compressors use branch-circuit selection current (45A), not FLA (42A). × 125% = 56.25A min. 6 AWG THW = 65A ✓.",
  },
  {
    questionId: 32,
    topic: "Motor Branch Circuits",
    question: "The motor ______ rating is used to provide separate motor overload protection.",
    answer: "full-load current",
    mnemonic: "\"The NAMEPLATE's FLC — Full-Load Current — is the OL setpoint. Use the motor's own number.\"",
    hook: "Overload protection is sized to actual nameplate FLC, not NEC table FLC. The motor tells you its own full-load current.",
  },
  {
    questionId: 33,
    topic: "Motor Branch Circuits",
    question: "Conductors supplying a single motor shall have ampacity not less than ______ of motor FLC.",
    answer: "125%",
    mnemonic: "\"1-2-5 for the WIRES. One quarter more. Disconnects get 115, wires get 125.\"",
    hook: "NEC 430.22(A): conductor ampacity ≥ 125% of table FLC. The extra 25% handles motor starting current without overheating.",
  },
  {
    questionId: 34,
    topic: "Class II Hazardous Locations",
    question: "Dry-type transformers in Class II, Div 2 shall operate at not over ______ nominal.",
    answer: "600 V",
    mnemonic: "\"600V is the NEC's standard cutoff for most equipment — dust locations are no different.\"",
    hook: "Class II Div 2 dry transformers are limited to 600V nominal to reduce arc energy and ignition risk from dust.",
  },
  {
    questionId: 35,
    topic: "Class II Hazardous Locations",
    question: "Temperature marking for Class II locations must be less than the ______ of the specific dust.",
    answer: "ignition temperature",
    mnemonic: "\"Don't IGNITE the dust. Surface temp must stay BELOW the IGNITION temperature.\"",
    hook: "If equipment surface gets hotter than the dust's ignition temperature, a dust layer can catch fire. The T-code keeps surfaces safe.",
  },
  {
    questionId: 36,
    topic: "Class II Hazardous Locations",
    question: "Flexible cord permitted in Class II, Div 1 when terminated with listed dust-tight connectors.",
    answer: "listed for extra-hard usage",
    mnemonic: "\"DUST = EXTRA HARD conditions. Extra-hard usage cord for extra-tough environments.\"",
    hook: "Class II is dusty and harsh — need the toughest cord rating. Not hard usage, not regular — EXTRA-hard usage.",
  },
  {
    questionId: 37,
    topic: "DC Motors & Generators",
    question: "Interpoles between main poles of a DC motor are connected in series with the ______ windings.",
    answer: "armature",
    mnemonic: "\"Inter-POLES help ARM-ature commutation. They're in SERIES with the arm.\"",
    hook: "Interpoles (commutating poles) are in series with the armature to cancel the armature's own magnetic field and reduce sparking at the brushes.",
  },
  {
    questionId: 38,
    topic: "DC Motors & Generators",
    question: "DC ______ motors are used for applications requiring constant speed and high starting torque.",
    answer: "compound",
    mnemonic: "\"COMPOUND = COMBINED best of both worlds: Series torque + Shunt speed stability.\"",
    hook: "Compound motor has both shunt (for constant speed) and series (for high starting torque) field windings — best of both.",
  },
  {
    questionId: 39,
    topic: "DC Motors & Generators",
    question: "A DC ______ operates on the principle that voltage is induced in a coil rotating in a magnetic field.",
    answer: "generator",
    mnemonic: "\"GENERATE voltage by spinning. Moving coil in magnetic field = GENERATOR.\"",
    hook: "Faraday's law: moving conductor in a magnetic field induces voltage. That's a generator, not a motor (motor converts V to motion).",
  },
  {
    questionId: 40,
    topic: "DC Motors & Generators",
    question: "A ______ motor has field wiring connected in both series and parallel with the armature.",
    answer: "compound",
    mnemonic: "\"SERIES + PARALLEL = COMPOUND. Two field connections = COMPOUND motor.\"",
    hook: "Series field winding + shunt (parallel) field winding = compound motor. Both connections, not just one.",
  },
  {
    questionId: 41,
    topic: "DC Motors & Generators",
    question: "______ DC motors have the highest starting torque.",
    answer: "Series",
    mnemonic: "\"SERIES motors are SERIOUS about torque. Cranes, hoists, traction: all use series motors.\"",
    hook: "Series motor: field current = armature current = massive flux at startup. F = BIL → maximum force. Never run unloaded!",
  },
  {
    questionId: 42,
    topic: "Class III & Intrinsically Safe Systems",
    question: "Nonincendive field wiring circuits in Class III, Div 1 shall be installed in which conduit types?",
    answer: "I and III",
    mnemonic: "\"Class III + nonincendive = I and III. Skip the middle child (II).\"",
    hook: "The answer I and III for Class III locations — skip Type II. Odd-numbered types (I and III) for Class III nonincendive wiring.",
  },
  {
    questionId: 43,
    topic: "Class III & Intrinsically Safe Systems",
    question: "IS circuit conductors may share raceways with non-IS circuits when all non-IS conductors are in ______ metal-sheathed or metal-clad cables.",
    answer: "grounded",
    mnemonic: "\"IS sharing requires GROUNDED cables — ground keeps fault energy away from IS circuits.\"",
    hook: "The ground path on the non-IS cables ensures any fault current goes to ground rather than energizing the IS circuit and creating a spark hazard.",
  },
  {
    questionId: 44,
    topic: "Motor Overload Protection",
    question: "Minimum OL protection — 40 hp, 208 V, 3Ø, nameplate 82 A, SF 1.15, starting NOT a problem.",
    answer: "84.5 A",
    mnemonic: "\"82 × 103% ≈ 84.5. Just above FLA — minimum trip level with safety margin.\"",
    hook: "Minimum overload protection is set just above actual running current with a small margin. 82 × 1.031 ≈ 84.5A.",
  },
  {
    questionId: 45,
    topic: "Motor Overload Protection",
    question: "Maximum OL protection — 25 hp, 240 V, 3Ø, 63 A, SF 1.05, starting IS a problem.",
    answer: "140 A",
    mnemonic: "\"This answer is 140A — verify with NEC 430.52 table for the specific motor and OCPD type.\"",
    hook: "When starting is a problem, check both the overload and the branch-circuit OCPD maximums. Confirm against the NEC table for your specific situation.",
  },
  {
    questionId: 46,
    topic: "Motor Overload Protection",
    question: "Max OL for a 5 hp, 240 V, 1Ø motor — SF 1.15, nameplate FLC 31.5 A.",
    answer: "39.375 A",
    mnemonic: "\"31.5 × 1.25 = 39.375. SF ≥ 1.15 = 125% every time, one phase or three.\"",
    hook: "Single-phase, 3-phase — same percentage rules apply. 125% of 31.5A = 39.375A. No rounding needed (it's the exact calc).",
  },
  {
    questionId: 47,
    topic: "Motor Disconnect Sizing",
    question: "Minimum current rating of disconnect for 7.5 hp, 230 V, 1Ø motor.",
    answer: "46 A",
    mnemonic: "\"Table FLC: 7.5hp/230V/1Ø = 40A. × 115% = 46A. Forty times one-fifteen = forty-six.\"",
    hook: "NEC Table 430.248: 7.5hp at 230V single-phase = 40A. Disconnect = 40 × 115% = 46A.",
  },
  {
    questionId: 48,
    topic: "Motor Disconnect Sizing",
    question: "Minimum HP switch rating for 30 hp, 460 V, 3Ø Design B motor, Code Letter G.",
    answer: "40 HP",
    mnemonic: "\"Calculate LRC with Code G (up to 6.29 kVA/hp), then find the HP switch that handles it — answer is 40 HP.\"",
    hook: "LRC = 30 × 6.29 × 1000 ÷ (460 × 1.732) ≈ 237A. Check NEC Table 430.251(B) — 40HP switch at 460V handles that LRC.",
  },
  {
    questionId: 49,
    topic: "Motor Branch Circuits",
    question: "Minimum ampacity and THW conductor for 3Ø, 100 hp, 460 V squirrel-cage motor.",
    answer: "155 A / 2/0 AWG",
    mnemonic: "\"100hp/460V = 124A table. × 125% = 155A. 1/0 AWG = 150A (not enough) → 2/0 AWG = 175A ✓\"",
    hook: "Always round UP in conductor sizing. 155A required. 1/0 = 150 (too small). 2/0 = 175 (just right).",
  },
  {
    questionId: 50,
    topic: "Photoelectric & Proximity Sensors",
    question: "A photoelectric output that triggers when receiver gets sufficient light is called ______.",
    answer: "light operate",
    mnemonic: "\"LIGHT = LIGHT OPERATE. See the light, operate. Simple.\"",
    hook: "Light operate = output ON when light IS received. Dark operate = output ON when light is NOT received (beam broken).",
  },
  {
    questionId: 51,
    topic: "Photoelectric & Proximity Sensors",
    question: "A photoelectric output that changes state when light on the receiver drops is called ______.",
    answer: "dark operate",
    mnemonic: "\"Goes DARK → goes active. DARK OPERATE = triggered by darkness (no light).\"",
    hook: "When the beam is blocked (goes dark), the sensor activates. Used for object detection on a conveyor (object blocks beam = dark operate).",
  },
  {
    questionId: 52,
    topic: "Photoelectric & Proximity Sensors",
    question: "Which is NOT one of the four parameters commonly used to describe photoelectric operation?",
    answer: "response",
    mnemonic: "\"The four parameters: SOURCE, SENSING MODE, OUTPUT, RANGE. Response is NOT one of them.\"",
    hook: "Photoelectric parameters: light source (LED type), sensing mode (through/retro/diffuse), output type (NPN/PNP), sensing range. 'Response' isn't a standard parameter name.",
  },
  {
    questionId: 53,
    topic: "Photoelectric & Proximity Sensors",
    question: "Which photoelectric scanning method is more reliable for long-range sensing?",
    answer: "direct scan",
    mnemonic: "\"DIRECT and DISTANT — direct scan sends beam straight from emitter to receiver. No reflection = no loss.\"",
    hook: "Direct (through-beam) scan has emitter and receiver separated — strongest signal path. Best for long distances.",
  },
  {
    questionId: 54,
    topic: "Photoelectric & Proximity Sensors",
    question: "Which photoelectric method should NOT be used when the product surface is shiny or reflective?",
    answer: "retroreflective scan",
    mnemonic: "\"RETRO reflects off a target — shiny objects trick it into thinking a reflector is there.\"",
    hook: "Retroreflective uses a reflector to send beam back. Shiny objects also reflect — sensor can't tell them apart. Avoid on glossy products.",
  },
  {
    questionId: 55,
    topic: "Photoelectric & Proximity Sensors",
    question: "Proximity sensors can be capacitive, inductive, or ______.",
    answer: "ultrasonic",
    mnemonic: "\"C-I-U: Capacitive, Inductive, Ultrasonic. Three types of proximity. CIU = 'See I Use' three types.\"",
    hook: "Three proximity types: inductive (metal only), capacitive (any material), ultrasonic (sound waves, any material, longer range).",
  },
  {
    questionId: 56,
    topic: "Photoelectric & Proximity Sensors",
    question: "Most common method to provide electrical isolation between input and output of an SSR?",
    answer: "optical coupling",
    mnemonic: "\"LIGHT crosses the gap, not ELECTRICITY. OPTICAL coupling = isolation by light.\"",
    hook: "Same as opto-isolator concept — LED flashes light to phototransistor. Electrical isolation with signal transfer.",
  },
  {
    questionId: 57,
    topic: "Class II Hazardous Locations",
    question: "Each luminaire in Class II, Div 1 shall be ______ and marked for max lamp wattage.",
    answer: "identified for the location and clearly marked",
    mnemonic: "\"Dusty lights need an ID tag and a watt limit — identified and marked.\"",
    hook: "Luminaires in Class II Div 1 must be listed/identified for that specific location AND have max wattage marked — dust buildup changes heat dissipation.",
  },
  {
    questionId: 58,
    topic: "Class II Hazardous Locations",
    question: "In Class II, Div 2, motor-generator max external temperature shall comply with ______.",
    answer: "500.8(C)(2)",
    mnemonic: "\"500.8(C)(2) — 500 for hazardous, 8 for equipment, C for Class II motors, 2 for Div 2.\"",
    hook: "NEC 500.8(C)(2) sets the temperature limits for equipment in Class II Div 2. The section reference is the answer.",
  },
  {
    questionId: 59,
    topic: "Class II Hazardous Locations",
    question: "Boxes and fittings in Class II, Div 1 shall have threaded bosses for conduit and shall be ______.",
    answer: "dusttight",
    mnemonic: "\"Class II = DUST. Div 1 = WORST. Boxes = DUST-TIGHT. Seal out the dust completely.\"",
    hook: "Dusttight means gasketed to prevent dust entry. Div 1 = worst-case dust = tightest enclosure requirements.",
  },
  {
    questionId: 60,
    topic: "Class II Hazardous Locations",
    question: "Which wiring method is NOT permitted in Class II, Div 1?",
    answer: "non-metallic sheathed cable",
    mnemonic: "\"Same rule as Class I: NO PLASTIC in hazardous zones. NM cable is out.\"",
    hook: "NM cable (plastic jacket, no armor) is forbidden in all Division 1 hazardous locations — Class I or II. Metal only.",
  },
  {
    questionId: 61,
    topic: "Class I Hazardous Locations",
    question: "Type PLTC or PLTC-ER cable for Class 2/3 circuits including cable tray permitted in ______ locations.",
    answer: "Class I, Division 2",
    mnemonic: "\"PLTC = Power Limited Tray Cable. PLTC allowed in CLASS I DIV 2 — where gas is unlikely but possible.\"",
    hook: "Division 2 is less severe — more wiring methods allowed, including PLTC-ER. Division 1 requires metallic conduit.",
  },
  {
    questionId: 62,
    topic: "Class I Hazardous Locations",
    question: "Sealing fitting in conduit leaving Class I, Div 2 shall be permitted to be installed ______.",
    answer: "on either side of the boundary within 10 ft",
    mnemonic: "\"Div 2 boundary seals: TEN FEET from the boundary, on EITHER side. 10 feet of flexibility.\"",
    hook: "Div 1 requires seal within 18 inches of the enclosure. Div 2 boundary seals can be either side within 10 ft — more flexibility.",
  },
  {
    questionId: 63,
    topic: "Class III & Intrinsically Safe Systems",
    question: "PVC, RTRC, and HDPE conduit encased in concrete shall have a minimum envelope thickness of ______.",
    answer: "2 inches",
    mnemonic: "\"2-INCH concrete wrap. Concrete is the armor for plastic conduit. Two inches thick.\"",
    hook: "Non-metallic conduits (PVC, RTRC, HDPE) need 2 inches of concrete encasement to provide protection equivalent to metal conduit.",
  },
  {
    questionId: 64,
    topic: "Class III & Intrinsically Safe Systems",
    question: "In Class III locations, ______ shall be grounding type, minimize fiber accumulation, and prevent sparks/molten particles.",
    answer: "receptacles and attachment plugs",
    mnemonic: "\"Plug in safely: Class III receptacles and plugs must be GROUNDED, FIBER-RESISTANT, SPARK-FREE.\"",
    hook: "Three requirements for Class III outlets: grounding type (no floating ground), designed to keep fibers out, contain any arcing.",
  },
  {
    questionId: 65,
    topic: "ESD & General",
    question: "An ESD event is the rapid flow of electrons between two bodies of ______.",
    answer: "unequal charge",
    mnemonic: "\"ESD = electrons JUMPING from HIGH charge to LOW charge. UNEQUAL charges attract and discharge.\"",
    hook: "ESD is exactly like a spark — charge builds on one object, finds a path to a lower-charge object, and electrons rush across. Unequal charge = potential difference = current flow.",
  },
];
